-- https://school.programmers.co.kr/learn/courses/30/lessons/131533
-- 상품 별 오프라인 매출 구하기

SELECT P.PRODUCT_CODE, O.SALES_AMOUNT * P.PRICE AS SALES
FROM PRODUCT P
    JOIN OFFLINE_SALE O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC