-- https://school.programmers.co.kr/learn/courses/30/lessons/293257
-- 물고기 종류 별 잡은 수 구하기

SELECT COUNT(FI.FISH_TYPE) AS FISH_COUNT, FNI.FISH_NAME
FROM FISH_INFO FI
    INNER JOIN FISH_NAME_INFO FNI
        ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FNI.FISH_NAME
ORDER BY FISH_COUNT DESC